language: node_js
node_js:
- '6.10'
deploy:
  skip_cleanup: true
  provider: script
  script: yarn deploy
  on:
    branch: master
env:
  secure: SLTWWsM5vmHu/uy/rIK6tux39QD/2+MQfd1AdHbG2mUOqiHgaSJuNPF4tuXhCJqkATFAhzuGLwLXBUiB4I7O37jbydw3dXi7ApKqZDx7d2nfOSurrlrXtQwQRtqkmp7QYsBTBq3jhIlzC5+i0K24fEmqi82yrSybuyIxf3WdflxUAHW7lcTm71LPFG9Las/oCmKVK/A/mxkaGzcMy4PU2yOaYpATQmV9IrWEoQP4CWLQD9IQRfwI1zwPEX4HFfTb1HiWAfQv6BRrcR9AEtV/TO4b1LdjMwZ30Me2xAe4XaB9a41dIWPJlf3Hw6PCed//Y+l6+4Wr1dURuINNFPNzLTkRdQ8A439X6cEwG5ETpcyHQiKe8PTf2VkyaihQsDJk5noubOJ7u5p1cghaiPmcjZspvaz0V/x0gNIP74WUJhD7KWWWuwvCqvB+uPsE8siNxk0bgVBSND0xNv/6qU1KRgm5LlbchWAPNc20y3KhYGJ9iBgCyWV9RNU3kwG7iAbcJCJvaGJD5HN5zxcXa6h3/6gpxLo/ls3Rm9WDPRC9lF5WsFvNlJAlSZ+TmPy1TKUbf8u8ljO+68YdB9MhGK13HiF8yuYAGb+VsGSodmtn/ELRiycLkJWUHu0vFvFRY0n6VpIfm1rez45HMBqA/3f8wesjlHGE8beV2ten20C2Pi0=
