language: node_js
node_js:
- node
- iojs
- '6.10'
deploy:
  skip_cleanup: true
  provider: script
  script: yarn deploy
  on:
    branch: master
env:
  secure: GV7YQ02AECeJbYZIFP5YaHSDBBa+n365NSDGxl/CzKb5Gh6PUf1kYugkAH03QLvqI9H+W/8QH68+C8N4q/oovzAK7yqWS8orpCU/V8LL0dI/zgX5TopYXDZ5wuKbwRcIwUFtRhrCQz6qNEX98ZeoPZn1QB8iD7l1D54NU6pYaBPKBPxN3TEybhc6OeWykyzFSml55etZPJJI4xdPuhYCxmHcQJ7hLauG08wsc9nIBcXCKNBxSAd3yLo46lWvCOi0t4x76z13ILYD1UkCgxRunLyjNMIpkMFGKBM+e56SRPouEgg3b5dbmEgjIyXJrbr5CgEbElqvyb3TYY4SfCRH3K6GeoFQfs8tF8mJnm+79SV1wJu5bO302Hc250PX5Hlo4jzEEb9xJhAlDMkAQQC7MlLuUkKxp0oWz0YkPB4fqdIqCrjUadeIGN+jhE2hPhtNsUU4wC8N4qPuS2jVWDyU96HV9L8vXR98pkOWMu8mQlSk78VlcI2x+vhA/EppvpclMTwdH6KiVotl3Uax99mQVavj3Mhmuqi6NXtr6p0o/5n7iSVQN3h6ckj4NZKXNQlemEw65SmXSimwpbiNzFGuQazwRQqm8eO+vRyffgA5Yhi1ssXKmJ2e50p5v88RhgwYbxoBvrmGhqFw24Xqntz/VPxy+aHPAORUozXAFaJqqcI=
